version: '2'
services:
  jh20191209-app:
    image: jh20191209
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jh20191209-postgresql:5432/jh20191209
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jh20191209-postgresql:
    extends:
      file: postgresql.yml
      service: jh20191209-postgresql
